version: '3'

services:
  malwarebytes_dev:
    container_name: malwarebytes_dev
    build:
      context: .
    working_dir: /extension
    command: cextrun -d
    volumes: 
      - .:/extension
    env_file:
      - .malwarebytes_test.env

  malwarebytes_bash:
    container_name: malwarebytes_bash
    build:
      context: .
    working_dir: /extension
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
    env_file:
      - .malwarebytes_test.env

  malwarebytes_test:
    container_name: malwarebytes_test
    build:
      context: .
    working_dir: /extension
    command: extension-test
    volumes:
      - .:/extension
    env_file:
      - .malwarebytes_test.env
