[tool.poetry]
name = "malwarebytes"
version = "0.1.0"
description = "Malwarebytes OneView is a multi-tenant console where you can manage Malwarebytes MSP accounts, Malwarebytes Nebula subscriptions, invoicing, and integrations."
authors = ["Ingram Micro"]
license = "Apache Software License 2.0"
packages = [
    { include = "malwarebytes" },
    { include = "connect_malwarebytes" }
]
readme = "./README.md"

[tool.poetry.plugins."connect.eaas.ext"]
"eventsapp" = "connect_malwarebytes.events:MalwarebytesEventsApplication"

[tool.poetry.dependencies]
python = ">=3.8,<4"
connect-eaas-core = ">=27.9,<28"
requests = "^2.28.2"
pycountry = "^22.3.5"
python-dateutil = "^2.8.2"
xlsxwriter = "^3.1.0"
pytest-mock = "^3.10.0"

[tool.poetry.dev-dependencies]
pytest = ">=6.1.2,<8"
pytest-cov = ">=2.10.1,<5"
pytest-mock = "^3.3.1"
mock = { version = "^4.0.3", markers = "python_version < '3.8'" }
coverage = { extras = ["toml"], version = ">=5.3,<7" }
flake8 = ">=3.8,<6"
flake8-bugbear = ">=20,<23"
flake8-cognitive-complexity = "^0.1"
flake8-commas = "~2.0"
flake8-future-import = "~0.4"
flake8-import-order = "~0.18"
flake8-broken-line = ">=0.3,<0.7"
flake8-comprehensions = "^3.3.1"
flake8-debugger = "^4.0.0"
flake8-eradicate = "^1.0.0"
flake8-string-format = "^0.3.0"
pytest-asyncio = "^0.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = "tests"
addopts = "--cov=connect_malwarebytes --cov=malwarebytes --cov-report=term-missing --cov-report=html --cov-report=xml"

[tool.coverage.run]
omit = [
    "tests/*",
    "venv*/*",
    "malwarebytes/account/infrastructure/*",
    "connect_malwarebytes/events.py",
    "connect_malwarebytes/connect/request.py",
    "connect_malwarebytes/connect/excel.py",
]
relative_files = true
branch = true

[tool.coverage.report]
omit = [
    "pragma: no cover",
    "def __str__",
    "def __repr__",
    "import",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
]
